import React from 'react';
import type { Metadata } from 'next';
import { Breadcrumb } from '@/components/layout/Breadcrumb';

export const metadata: Metadata = {
  title: 'Terms of Service | លក្ខខណ្ឌប្រើប្រាស់',
  description: 'Terms and conditions for utilizing the free online tools on KhmerTools.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8 py-2 sm:py-6">
      <Breadcrumb items={[{ label: 'Terms of Service' }]} />

      <div className="bg-white dark:bg-slate-900 rounded-3xl p-6 sm:p-10 border border-slate-200/80 dark:border-slate-800/80 shadow-xs space-y-6">
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">
          Terms of Service • លក្ខខណ្ឌប្រើប្រាស់
        </h1>

        <p className="text-xs text-slate-400">
          Last updated: September 2026
        </p>

        <div className="space-y-4 text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using KhmerTools (https://khmertools.com), you agree to comply with and be bound by these Terms of Service. If you do not agree, please discontinue using the website.
          </p>

          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            2. Permitted Use
          </h2>
          <p>
            You are free to use all tools, calculators, and converters provided on KhmerTools for personal, educational, commercial, or professional purposes without charge.
          </p>

          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            3. Disclaimer of Warranties
          </h2>
          <p>
            All tools and calculations on KhmerTools are provided on an &quot;as is&quot; and &quot;as available&quot; basis without warranty of any kind. While we make every effort to ensure algorithmic accuracy in our Khmer text normalizers, financial formulas, and date calculations, KhmerTools shall not be liable for any financial, business, or administrative decisions made based on outputs from these tools.
          </p>

          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            4. Intellectual Property
          </h2>
          <p>
            The software design, UI components, branding, and compilation of KhmerTools are protected by copyright. The raw outputs generated by tools belong entirely to you.
          </p>

          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            5. Changes to Terms
          </h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the website following any changes signifies acceptance of the revised terms.
          </p>
        </div>
      </div>
    </div>
  );
}
